export const allItemsMock = {
    data: {
        items: [
            {
                id: '737e9610-fff0-475a-8c06-50f23fa4bf6f',
                isFavorite: false,
                title: 'iPhone 6S Oro',
                description:
                    'Vendo un iPhone 6 S color Oro nuevo y sin estrenar. Me han dado uno en el trabajo y no necesito el que me compré. En tienda lo encuentras por 749 euros y yo lo vendo por 740. Las descripciones las puedes encontrar en la web de apple. Esta libre.',
                price: '740',
                email: 'iphonemail@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/iphone.png',
            },
            {
                id: 'ef83dda6-0a79-4de0-ac37-1823d6165b2e',
                isFavorite: false,
                title: 'Polaroid 635',
                description:
                    'Cámara clásica de fotos Polaroid, modelo 635. Las fotos son a super color. Está en perfectas condiciones y es fantástica para coleccionistas. Se necesitan carretes instax 20 para hacer fotos. Tamaño M.',
                price: '50',
                email: 'cameramail@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/camera.png',
            },
            {
                id: 'fdc2eb28-cf14-4c63-94aa-676f06df7bad',
                isFavorite: false,
                title: 'Bolso piel marca Hoss',
                description:
                    'Vendo bolso de piel marrón grande de la marca Hoss. Lo compré hace dos temporadas. Esta en perfectas condiciones, siempre se ha guardado en bolsa de tela para su conservación. Precio original de 400 euros. Lo vendo por 250 porque ya casi no me lo pongo. Tiene varios compartimentos dentro.',
                price: '250',
                email: 'bagmail@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/bag.png',
            },
            {
                id: '41ef2920-69e0-4076-bd03-d9d38d73f153',
                isFavorite: false,
                title: 'Reloj de Daniel Wellington',
                description:
                    'Reloj de la marca Daniel Wellington usado sólo un mes. Ahora me han regalado otro que me gusta más y es muy parecido; por eso lo vendo. Su precio en tienda son 149 pero lo vendo por 100 euros. Es con la esfera blanca y la correa de piel marron. ',
                price: '100',
                email: 'watchmail@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/watch.png',
            },
            {
                id: '8ea82aaf-10a7-4e9c-b20d-b609abe7c7f0',
                isFavorite: false,
                title: 'Coche antiguo americano',
                description:
                    'Coche antiguo americano de color marrón. Se tiene que cambiar el motor pero aparte de eso todo funciona correctamente. Interior de piel clara. Ideal para coleccionistas',
                price: '210000',
                email: 'carmail@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/car.png',
            },
            {
                id: 'fef0cb50-220b-4799-a423-13239fa3df7c',
                isFavorite: false,
                title: 'Barbacoa',
                description:
                    'Barbacoa en buen estado. La he usado pocas veces y está casi nueva. Ideal para fiestas y celebraciones',
                price: '120',
                email: 'barbecue@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/barbecue.png',
            },
            {
                id: '3c0fbc06-e545-428d-9e49-fa8779f196c0',
                isFavorite: false,
                title: 'Sofa de piel auténtica',
                description:
                    'Vendo sofá de piel negro. Tiene signos evidentes de uso, de ahí el precio. Es muy cómodo y bonito',
                price: '75',
                email: 'sofa@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/sofa.png',
            },
            {
                id: '333d68a6-1484-4d4a-b528-c2f4ddf03042',
                isFavorite: false,
                title: 'Vespa restaurada',
                description:
                    'Está restaurada y muy cuidada, con piezas originales y repintada una vez de color rojo carmín. Solo acepto ofertas serias',
                price: '1990',
                email: 'vespa@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/vespa.png',
            },
            {
                id: '1e912d18-7698-4e2d-a6d2-81b99a04ac34',
                isFavorite: false,
                title: 'Batidora',
                description: 'Está completamente nueva (no la he sacado de la caja). Me la regalaron pero no la quiero',
                price: '90',
                email: 'mixer@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/mixer.png',
            },
            {
                id: '020e98f5-6296-4617-a93c-102c5e95e91d',
                isFavorite: false,
                title: 'Mudanzas',
                description: 'Está completamente nueva (no la he sacado de la caja). Me la regalaron pero no la quiero',
                price: '90',
                email: 'moves@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/moves.png',
            },
            {
                id: '19a6e560-9035-4654-af49-9e59d0c3582c',
                isFavorite: false,
                title: 'Lavadora',
                description: 'Vendo lavadora comprada hace 1 año. Me cambio de piso y me urge venderla',
                price: '250',
                email: 'washer@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/washer.png',
            },
            {
                id: '9b041a55-11cb-43e7-8e34-eba721e09ef2',
                isFavorite: false,
                title: 'TV de 43 pulgadas',
                description: 'Televisor de 43 pulgadas. Funciona perfectamente. No tengo la base. Precio negociable',
                price: '400',
                email: 'tv@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/tv.png',
            },
            {
                id: '6312ac1d-2220-4237-9b70-2bf9592fb895',
                isFavorite: false,
                title: 'Piso en Clot',
                description: '60m2, en pleno mercado del Clot. Piso muy acogedor, reformado. Ideal para parejas',
                price: '288000',
                email: 'flat@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/flat.png',
            },
            {
                id: '3a87cfc4-887a-48bd-b42a-fd81344df088',
                isFavorite: false,
                title: 'Tocadiscos vintage',
                description: 'Muy bien cuidado! Regalo los discos de LP que se ve en las fotos',
                price: '325',
                email: 'turntable@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/turntable.png',
            },
            {
                id: 'ce26e9fc-bb95-4260-ba74-a102da8c785b',
                isFavorite: false,
                title: 'Nevera verde',
                description: 'Pequeñita, con un verde Chevrolet, muy de los 60!',
                price: '125',
                email: 'fridge@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/fridge.png',
            },
            {
                id: '3ec4c3f9-9c54-4d63-afd4-65efb3ac92b6',
                isFavorite: false,
                title: 'Cámara réflex',
                description: 'La vendo porque no la uso. No tengo ningún accesorio como la bolsa ni objetivos.',
                price: '240',
                email: 'analogue@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/analogue.jpg',
            },
            {
                id: '79e94e58-ea35-4266-81d5-a3afbe312992',
                isFavorite: false,
                title: 'Clases de piano',
                description:
                    'Doy clases de piano a particulares. Todas las edades. Llevo más de 20 años tocando el piano.',
                price: '5',
                email: 'piano@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/piano.jpg',
            },
            {
                id: 'b995c8f7-e45e-4efd-b192-0e198aa41eff',
                isFavorite: false,
                title: 'Material de oficina',
                description:
                    'Vendo mucho material de oficina, como bolígrafos, lápices, post-its, etc. Preguntad para más info',
                price: '12',
                email: 'pen@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/pen.jpg',
            },
            {
                id: 'be49eeb1-d427-4970-8574-382fcca90bfd',
                isFavorite: false,
                title: 'Macbook 13 pulgadas',
                description: 'Vendo Macbook porque me han regalado el nuevo. Este está usado pero en buen estado',
                price: '600',
                email: 'mac@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/mac.jpg',
            },
            {
                id: '4b493192-5eab-41a9-afea-f31763e9ef39',
                isFavorite: false,
                title: 'Cascos',
                description: 'Cascos usados. No son muy buenos, pero son bastante bonitos. Precio negociable',
                price: '20',
                email: 'headphones@wallapop.com',
                image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/headphones.jpg',
            },
        ],
    },
};
