export const itemsSortedByTitleMock = {
    items: [
        {
            id: '694507cc-97ba-4cc2-81fe-466707b1b3b8',
            isFavorite: false,
            title: 'Batidora',
            description: 'Está completamente nueva (no la he sacado de la caja). Me la regalaron pero no la quiero',
            price: '90',
            email: 'mixer@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/mixer.png',
        },
        {
            id: 'd55ad394-ca5c-466c-a15f-5fd2266ea1ce',
            isFavorite: false,
            title: 'Bolso piel marca Hoss',
            description:
                'Vendo bolso de piel marrón grande de la marca Hoss. Lo compré hace dos temporadas. Esta en perfectas condiciones, siempre se ha guardado en bolsa de tela para su conservación. Precio original de 400 euros. Lo vendo por 250 porque ya casi no me lo pongo. Tiene varios compartimentos dentro.',
            price: '250',
            email: 'bagmail@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/bag.png',
        },
        {
            id: 'cbd592e0-0b5f-4c26-ac1c-a2d602407ccd',
            isFavorite: false,
            title: 'Cascos',
            description: 'Cascos usados. No son muy buenos, pero son bastante bonitos. Precio negociable',
            price: '20',
            email: 'headphones@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/headphones.jpg',
        },
        {
            id: '49230444-a45d-4fc7-a233-642275d91d0c',
            isFavorite: false,
            title: 'Clases de piano',
            description: 'Doy clases de piano a particulares. Todas las edades. Llevo más de 20 años tocando el piano.',
            price: '5',
            email: 'piano@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/piano.jpg',
        },
        {
            id: '20aa70f7-bc00-4504-96e9-7f3a452dd193',
            isFavorite: false,
            title: 'Coche antiguo americano',
            description:
                'Coche antiguo americano de color marrón. Se tiene que cambiar el motor pero aparte de eso todo funciona correctamente. Interior de piel clara. Ideal para coleccionistas',
            price: '210000',
            email: 'carmail@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/car.png',
        },
        {
            id: 'a91ab110-5ec5-4d51-9a1b-bf90ecf2cb84',
            isFavorite: false,
            title: 'Macbook 13 pulgadas',
            description: 'Vendo Macbook porque me han regalado el nuevo. Este está usado pero en buen estado',
            price: '600',
            email: 'mac@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/mac.jpg',
        },
        {
            id: '13ba9b72-5731-44e0-a688-fb11bb476fe6',
            isFavorite: false,
            title: 'Material de oficina',
            description:
                'Vendo mucho material de oficina, como bolígrafos, lápices, post-its, etc. Preguntad para más info',
            price: '12',
            email: 'pen@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/pen.jpg',
        },
        {
            id: '8c7ea6ba-c715-44d7-b307-9820234d5108',
            isFavorite: false,
            title: 'Mudanzas',
            description: 'Está completamente nueva (no la he sacado de la caja). Me la regalaron pero no la quiero',
            price: '90',
            email: 'moves@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/moves.png',
        },
        {
            id: 'bd488809-5fb0-4507-9d0c-8a0583326700',
            isFavorite: false,
            title: 'Piso en Clot',
            description: '60m2, en pleno mercado del Clot. Piso muy acogedor, reformado. Ideal para parejas',
            price: '288000',
            email: 'flat@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/flat.png',
        },
        {
            id: 'e66ac31d-5962-41be-90fc-66481bbab340',
            isFavorite: false,
            title: 'Polaroid 635',
            description:
                'Cámara clásica de fotos Polaroid, modelo 635. Las fotos son a super color. Está en perfectas condiciones y es fantástica para coleccionistas. Se necesitan carretes instax 20 para hacer fotos. Tamaño M.',
            price: '50',
            email: 'cameramail@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/camera.png',
        },
        {
            id: '8f89182a-5c40-45ee-91a9-4b18e0017000',
            isFavorite: false,
            title: 'Reloj de Daniel Wellington',
            description:
                'Reloj de la marca Daniel Wellington usado sólo un mes. Ahora me han regalado otro que me gusta más y es muy parecido; por eso lo vendo. Su precio en tienda son 149 pero lo vendo por 100 euros. Es con la esfera blanca y la correa de piel marron. ',
            price: '100',
            email: 'watchmail@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/watch.png',
        },
        {
            id: '86e3247a-1040-44e4-8712-d22b52701621',
            isFavorite: false,
            title: 'Sofa de piel auténtica',
            description:
                'Vendo sofá de piel negro. Tiene signos evidentes de uso, de ahí el precio. Es muy cómodo y bonito',
            price: '75',
            email: 'sofa@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/sofa.png',
        },
        {
            id: '608a0472-cbca-48b4-9ac4-78b1331da86a',
            isFavorite: false,
            title: 'TV de 43 pulgadas',
            description: 'Televisor de 43 pulgadas. Funciona perfectamente. No tengo la base. Precio negociable',
            price: '400',
            email: 'tv@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/tv.png',
        },
        {
            id: '3d146ace-c6ef-48da-bdf4-7a4123ae3cdd',
            isFavorite: false,
            title: 'Tocadiscos vintage',
            description: 'Muy bien cuidado! Regalo los discos de LP que se ve en las fotos',
            price: '325',
            email: 'turntable@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/turntable.png',
        },
        {
            id: '9aa17637-d875-4380-883a-ed9ad858c44b',
            isFavorite: false,
            title: 'Vespa restaurada',
            description:
                'Está restaurada y muy cuidada, con piezas originales y repintada una vez de color rojo carmín. Solo acepto ofertas serias',
            price: '1990',
            email: 'vespa@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/vespa.png',
        },
        {
            id: '63468dbf-3d49-46fc-9e82-d2d19d150872',
            isFavorite: false,
            title: 'iPhone 6S Oro',
            description:
                'Vendo un iPhone 6 S color Oro nuevo y sin estrenar. Me han dado uno en el trabajo y no necesito el que me compré. En tienda lo encuentras por 749 euros y yo lo vendo por 740. Las descripciones las puedes encontrar en la web de apple. Esta libre.',
            price: '740',
            email: 'iphonemail@wallapop.com',
            image: 'https://frontend-tech-test-data.s3-eu-west-1.amazonaws.com/img/iphone.png',
        },
    ],
};
